### ISSUE TITLE
Default environment

### ISSUE THREAD

**Issue by pietercardoen** [sbabic/libubootenv#15]
Dear

For industrial embedded systems it is preferred to have a system which recovers when the environment gets corrupt. In current implementation, the fw_printenv and fw_setenv tool just fail when the environment is corrupt.

A default environment is supported by the tool but not used by default. The configuration file /etc/fw_env.config however is loaded as fallback and another file can be specified with argument -c. Isn't it better to also provide a default path for the default environment?

What's the reason to implement it this way?

Kind regards
Pieter Cardoen

**Comment by sbabic** [comment]
On 13.04.21 16:23, Pieter Cardoen wrote:
> Dear
> 

https://github.com/sbabic/libubootenv#contributing-to-the-project

Please send questions just to ML, not as issue.

> For industrial embedded systems it is preferred to have a system which 
> recovers when the environment gets corrupt.

In industrial application tge environment cannot get corrupted, see later.

> In current implementation, 
> the fw_printenv and fw_setenv tool just fail when the environment is 
> corrupt.

This is not correct. First, you have to set up U-Boot to support 
redundant copies else storing the environment is not power-cut safe. 
This guarantees that environment does not get corrupted.

If the environment is still corrupted, you can restore (the default) with
	fw_setenv -f <default file>

> 
> A default environment is supported by the tool but not used by default.

There is no default.

> The configuration file /etc/fw_env.config however is loaded as fallback 
> and another file can be specified with argument -c.

-f

> Isn't it better to 
> also provide a default path for the default environment?
> 
> What's the reason to implement it this way?

Tool must be compatible with older u-boot-fw-utils provided by U-Boot. 
The old fw_setenv had no default environment at all. The new tools are 
thought to be a replacement for the past, and they should still work in 
old scripts, that is where there is no support for a default (called 
embedded in U-Boot) environment. Because the file is not defined and its 
name is or could be different between Yocto / OE / Debian /... (and name 
was already changed in OE), there is no default path for this file.


> 
> Kind regards
> Pieter Cardoen
> 

Best regards,
Stefano Babic


-- 
=====================================================================
DENX Software Engineering GmbH,      Managing Director: Wolfgang Denk
HRB 165235 Munich, Office: Kirchenstr.5, D-82194 Groebenzell, Germany
Phone: +49-8142-66989-53 Fax: +49-8142-66989-80 Email: ***@***.***
=====================================================================

**Comment by pietercardoen** [comment]
Hi Stefano

Thanks for the quick reply.

Indeed redundant environment avoids having a corrupt environment. We however have a number of devices with older bootloader versions in the field with no redundant environment configured. Updating bootloader in the field is not always wanted so we need to continue working with it.

Answer is clear. I will close the ticket.

Kind regards
Pieter
